name: telegram local api build
on: workflow_dispatch
  input:
    tag:
      description: The release tag
      type: string
      required: false
jobs:
  check:
    name: Check Access
    runs-on: ubuntu-latest
    steps:
      - name: "Check access"
        uses: "lannonbr/repo-permission-check-action@2.0.0"
        with:
          permission: "write"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: update dependence
        run: sudo apt-get update && sudo apt-get upgrade
      - name: install dependencies
        run: sudo apt install -y openssl zlib1g gcc g++ gperf cmake make curl wget git
      - name: build	
        run: | 
          cd /tmp && git clone --recursive https://github.com/tdlib/telegram-bot-api.git
          cd telegram-bot-api
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --target install -j$(nproc)
          cd ../..
          ls -l telegram-bot-api/bin/telegram-bot-api*
          cp telegram-bot-api/bin/telegram-bot-api telegram-bot-api-binary
      - name: release
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: telegram-bot-api-binary
        



      
