name: telegram local api build
on:
  watch:
    types: [started]
jobs:
  name: build
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
      name: checkout
      checkout:
        repo: https://github.com/tdlib/telegram-bot-api.git
        branch: master
        depth: 1	
    - name: update depedence
      run: sudo apt-get update && sudo apt-get upgrade
    - name: install dependencies
      run: sudo apt install -y openssl zlib1g gcc g++ gperf cmake make curl wget git
    - name: build	
      run: |
        cd telegram-bot-api
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --target install	
