name: telegram local api build
on: [star]
jobs:
	runs-on: ubuntu-latest
	steps:
		- uses: actions/checkout@v2
			name: checkout
			checkout:
				repo: https://github.com/tdlib/telegram-bot-api.git
				branch: master
				depth: 1	
		- name: build	
			run: |
				cd telegram-bot-api
				mkdir build
				cd build
				cmake -DCMAKE_BUILD_TYPE=Release ..
				cmake --build . --target install	
